apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: helloworld-go
      annotations:
        autoscaling.knative.dev/maxScale: "20"
        autoscaling.knative.dev/target: "10"
    spec:
      serviceAccountName: cr-ee-account
      containers:
        - image: enterprise-registry-registry.cn-shanghai.cr.aliyuncs.com/knative-demo/helloworld-go:v0.1
          ports:
            - name: http1
              containerPort: 8080
          env:
            - name: TARGET
              value: "enterprise secret"