apiVersion: v1
kind: ServiceAccount
metadata:
  name: cr-ee-account
imagePullSecrets:
  - name: cr-ee-secret
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cr-ee-account-role
rules:
  - apiGroups: ["serving.knative.dev"]
    resources: ["services"]
    verbs: ["get", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cr-ee-account-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-ee-account-role
subjects:
  - kind: ServiceAccount
    name: cr-ee-account
    namespace: default
---